repos:
    - repo: local
      hooks:
          - id: check-version-increment
            name: Check Version Increment
            entry: python scripts/hooks/pre-push/check_version_increment.py
            language: system
            pass_filenames: false
            stages: [pre-push]

          - id: tests
            name: Run Python Tests
            entry: uv run test
            language: system
            pass_filenames: false
            stages: [pre-push]

          - id: prettier-with-jinja
            name: Prettier (with Jinja support)
            entry: bun run prettier -c
            language: system
            types_or:
                [javascript, jsx, ts, tsx, css, scss, sass, less, yaml, json, markdown, html, jinja]
            stages: [pre-push]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.9
      hooks:
          - id: ruff
            stages: [pre-push]
          - id: ruff-format
            stages: [pre-push]
