name: Auto Version Tag

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version tag
        uses: Jorricks/action-python-autotagging@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src/your_package/__about__.py  # Path to your version file
          variable: __version__              # Name of the version variable
